// One command for Phase 4: the robustness suites in dependency order, then
// PHASE4_RESULTS.md from the artifacts they produce. Every number in the
// results file is read from an artifact written by a run; nothing is typed in.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

if (!process.env.WHISPER_MODEL) {
  for (const c of ['.cache/whisper/ggml-medium.en.bin', '.cache/whisper/ggml-small.en.bin', '.cache/whisper/ggml-base.en.bin']) {
    if (fs.existsSync(c)) { process.env.WHISPER_MODEL = path.resolve(c); break; }
  }
}
const run = (args, extraEnv = {}) => spawnSync('node', args, { stdio: 'inherit', env: { ...process.env, ...extraEnv } });

const STEPS = [
  { id: 'rules', label: 'Phase 4 rules in Node (dates, masks, groups)', args: ['tools/test_phase4.mjs'],
    artifact: 'artifacts/phase4_rules.json' },
  { id: 'dom',   label: 'scanner + writer against the Phase 4 fixtures', args: ['tools/test_phase4_dom.mjs'],
    artifact: 'artifacts/phase4_dom.json' },
  { id: 'form',  label: 'the whole session over the Phase 4 shapes (exit criterion)', args: ['tools/test_phase4_form.mjs'],
    artifact: 'artifacts/phase4_form.json' },
  // The neighbours Phase 4 touched. domwrite and fieldgraph changed shape, so
  // their own suites are the regression that says Phases 1 and 2 still hold.
  { id: 'fieldgraph', label: 'Phase 1 scanner (regression)', args: ['tools/test_fieldgraph.mjs'],
    artifact: 'artifacts/phase1_fieldgraph.json' },
  { id: 'domwrite',   label: 'Phase 2 writer (regression)', args: ['tools/test_domwrite.mjs'],
    artifact: 'artifacts/phase2_domwrite.json' },
  { id: 'normalize',  label: 'Phase 2 normalisation (regression)', args: ['tools/test_normalize.mjs'],
    artifact: 'artifacts/phase2_normalize.json' },
];

const docOnly = process.argv.includes('--doc-only');
const status = {};
for (const s of STEPS) {
  if (docOnly) { status[s.id] = null; continue; }
  console.log(`\n=== ${s.label} ===`);
  const t0 = Date.now();
  const r = run(s.args, s.env || {});
  status[s.id] = { code: r.status, ms: Date.now() - t0 };
  if (r.status !== 0) console.log(`  (${s.id} exited ${r.status})`);
}

/** Pass/fail counts read out of the artifact the suite itself wrote. */
function counts(file) {
  try {
    const j = JSON.parse(fs.readFileSync(file, 'utf8'));
    const rs = j.results || j.cases || [];
    const pass = rs.filter(r => r.ok).length;
    return { pass, fail: rs.length - pass, total: rs.length, at: j.at || null };
  } catch { return null; }
}

const rows = STEPS.map(s => {
  const c = counts(s.artifact);
  const st = status[s.id];
  // --doc-only reports the artifact's OWN timestamp rather than claiming a run
  // that did not happen in this pass.
  return `| ${s.label} | \`${s.args[0].replace('tools/', '')}\` | ${c ? `${c.pass}/${c.total}` : '-'} | ${
    st ? (st.code === 0 ? 'pass' : `EXIT ${st.code}`)
       : (c ? (c.at ? `from ${String(c.at).slice(0, 19)}Z` : 'from its last run') : 'no artifact')} |`;
});

const md = `# Phase 4 results

Generated by \`node tools/phase4.mjs\`${docOnly ? ' --doc-only' : ''} on ${new Date().toISOString()}.
Every number below is read from the artifact the named suite wrote; none is typed in.

| Suite | File | Assertions | Status |
|---|---|---|---|
${rows.join('\n')}

See [PHASE4.md](./PHASE4.md) for what each suite claims and what it does not.
`;
fs.writeFileSync('PHASE4_RESULTS.md', md);
console.log(`\nwrote PHASE4_RESULTS.md`);
process.exit(Object.values(status).some(s => s && s.code !== 0) ? 1 : 0);
