// One command for Phase 2: every suite in dependency order, then
// PHASE2_RESULTS.md from the artifacts they produce.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

// The whisper model is resolved here so every suite sees the same one.
if (!process.env.WHISPER_MODEL) {
  for (const c of ['.cache/whisper/ggml-medium.en.bin', '.cache/whisper/ggml-small.en.bin', '.cache/whisper/ggml-base.en.bin']) {
    if (fs.existsSync(c)) { process.env.WHISPER_MODEL = path.resolve(c); break; }
  }
}
const run = (args) => spawnSync('node', args, { stdio: 'inherit', env: process.env });

const STEPS = [
  { id: 'selftest',  label: 'local self-test',                       args: ['tools/selftest.mjs'] },
  { id: 'normalize', label: 'normalisation + extraction (pure)',     args: ['tools/test_normalize.mjs'] },
  { id: 'domwrite',  label: 'DOM writing against real React',        args: ['tools/test_domwrite.mjs'] },
  { id: 'readback',  label: 'PRD 20-item read-back round trip',      args: ['tools/test_readback.mjs'] },
  { id: 'voicefill', label: 'one full form by voice (exit criterion)', args: ['tools/test_voicefill.mjs'] },
];
// Re-score the read-back clips with every model in WHISPER_MODELS (comma
// separated), so the per-model table is computed on identical audio.
const RESCORE = (process.env.WHISPER_MODELS || '').split(',').map(x => x.trim()).filter(Boolean);

const status = {};
let n = 0;
for (const s of STEPS) {
  n++;
  console.log(`\n─── ${n}/${STEPS.length}  ${s.label} ───`);
  const r = run(s.args);
  status[s.id] = r.status === 0 ? 'PASS' : (r.status === 2 ? 'BLOCKED' : 'FAIL');
  if (r.status !== 0 && s.id === 'selftest') { console.error('\nSelf-test failed; stopping.\n'); break; }
  if (s.id === 'readback' && RESCORE.length) {
    console.log(`\n─── read-back rescore across ${RESCORE.length} STT models (same clips) ───`);
    run(['tools/rescore_readback.mjs', ...RESCORE]);
  }
}

const read = (p) => { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } };
const norm = read('artifacts/phase2_normalize.json');
const dw = read('artifacts/phase2_domwrite.json');
const rb = read('artifacts/phase2_readback.json');
const rbm = read('artifacts/phase2_readback_models.json');
const vf = read('artifacts/phase2_voicefill.json');
const count = (o) => o ? `${o.results.filter(r => r.ok).length} pass / ${o.results.filter(r => !r.ok).length} fail` : 'not run';
const overall = Object.keys(status).length === STEPS.length && Object.values(status).every(v => v === 'PASS');

let modelRows = '';
if (rbm) for (const [name, per] of Object.entries(rbm)) {
  modelRows += `| ${name} | ${per.naive}/${per.n} (${Math.round(per.naive / per.n * 100)}%) | ${per.tuned}/${per.n} (${Math.round(per.tuned / per.n * 100)}%) | ${per.tuned / per.n >= 0.9 ? 'PASS' : 'FAIL'} |\n`;
}

const doc = `# Phase 2 results

Generated by \`npm run phase2\` on ${new Date().toISOString().slice(0, 10)}.

**Verdict: ${overall ? 'PASS' : 'INCOMPLETE'}**

| Suite | Result | Detail |
|---|---|---|
| Local self-test | ${status.selftest ?? 'not run'} | manifest, contracts, parse, secrets, plumbing |
| Normalisation + extraction | ${status.normalize ?? 'not run'} | ${count(norm)} |
| DOM writing (real React) | ${status.domwrite ?? 'not run'} | ${count(dw)} |
| 20-item read-back round trip | ${status.readback ?? 'not run'} | naive ${rb?.naiveHits ?? '?'}/${rb?.items ?? '?'}, tuned ${rb?.tunedHits ?? '?'}/${rb?.items ?? '?'} (${rb ? path.basename(rb.model) : '?'}) |
| Full form by voice | ${status.voicefill ?? 'not run'} | ${count(vf)} |

## Read-back round trip

Real Rime synthesis of the shipped confirmation utterance ("Let me read that
back. <value>. Is that correct?"), real STT, exact-match extraction. The PRD
bar is 90%. Both arms carry the same phrase; only the rendering of the value
differs.

| STT model | naive | tuned | bar |
|---|---|---|---|
${modelRows || '| (rescore not run) | | | |'}

Clips: \`eval/clips/{naive,tuned}/\`. Raw: \`artifacts/phase2_readback*.json\`.

## Reproducing

\`\`\`bash
npm run browser        # Chrome for Testing; stable ignores --load-extension
npm run stt:install    # whisper.cpp + model, for the harness STT
npm run phase2
\`\`\`
`;
fs.writeFileSync('PHASE2_RESULTS.md', doc);
console.log(`\nWrote PHASE2_RESULTS.md — verdict ${overall ? 'PASS' : 'INCOMPLETE'}\n`);
process.exit(overall ? 0 : 1);
