// One command for Phase 3: every suite in dependency order, then
// PHASE3_RESULTS.md from the artifacts they produce. Every number in the
// results file is read from an artifact written by a run; nothing is typed in.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

if (!process.env.WHISPER_MODEL) {
  for (const c of ['.cache/whisper/ggml-medium.en.bin', '.cache/whisper/ggml-small.en.bin', '.cache/whisper/ggml-base.en.bin']) {
    if (fs.existsSync(c)) { process.env.WHISPER_MODEL = path.resolve(c); break; }
  }
}
const run = (args) => spawnSync('node', args, { stdio: 'inherit', env: process.env });
const RUNS = process.env.BARGEIN_RUNS || '20';

const STEPS = [
  { id: 'selftest',  label: 'local self-test',                                      args: ['tools/selftest.mjs'] },
  { id: 'core',      label: 'barge-in core, attacked in Node (pure)',                args: ['tools/test_session_core.mjs'] },
  { id: 'stub',      label: 'delayed frames / stale tail / late timestamps (plumbing)', args: ['tools/test_bargein_stub.mjs'] },
  { id: 'bargein',   label: `${RUNS}+ real interruptions + scenarios (exit criterion)`, args: ['tools/test_bargein.mjs', '--runs', RUNS] },
  { id: 'voicefill', label: 'Phase 2 full form by voice (regression)',               args: ['tools/test_voicefill.mjs'] },
];

// --doc-only rebuilds PHASE3_RESULTS.md from the artifacts already on disk
// (every number still comes from a run; the suite statuses are derived from
// each artifact's own pass/fail counts, and the run time from the artifact).
const DOC_ONLY = process.argv.includes('--doc-only');
const read = (p) => { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } };
const status = {};
if (!DOC_ONLY) {
  for (let i = 0; i < STEPS.length; i++) {
    const s = STEPS[i];
    console.log(`\n─── ${i + 1}/${STEPS.length}  ${s.label} ───`);
    const r = run(s.args);
    status[s.id] = r.status === 0 ? 'PASS' : (r.status === 2 ? 'BLOCKED' : 'FAIL');
    if (r.status !== 0 && s.id === 'selftest') { console.error('\nSelf-test failed; stopping.\n'); break; }
  }
}
const core = read('artifacts/phase3_core.json');
const stub = read('artifacts/phase3_stub.json');
const bi = read('artifacts/phase3_bargein.json');
const vf = read('artifacts/phase2_voicefill.json');
if (DOC_ONLY) {
  const st = read('artifacts/selftest.json');
  const ok = (o) => (o ? (o.results ? o.results.every(r => r.ok) : o.every(r => r.status !== 'FAIL')) ? 'PASS' : 'FAIL' : 'not run');
  Object.assign(status, { selftest: ok(st), core: ok(core), stub: ok(stub), bargein: ok(bi), voicefill: ok(vf) });
}
const localDate = (d) => new Date(d || Date.now()).toLocaleDateString('en-CA');
const count = (o) => o ? `${o.results.filter(r => r.ok).length} pass / ${o.results.filter(r => !r.ok).length} fail` : 'not run';
const overall = Object.keys(status).length === STEPS.length && Object.values(status).every(v => v === 'PASS');
const st = bi?.stats || {};
const ms = (x) => (x == null ? '—' : `${Math.round(x)} ms`);
const yn = (b) => (b ? 'yes' : 'no');

const runRows = (bi?.runs || []).map(r =>
  `| ${r.run} | ${r.phase?.toFixed(2)} | ${r.hadAudio ? ms(r.stopLatencyMs) : 'pre-audio'} | ${r.hadAudio ? ms(r.stopLatencyIncSinkMs) : '—'} | ${r.hadAudio ? ms(r.detectToStopCallMs) : '—'} | ${r.heardCount ?? '?'}/${r.totalWords ?? '?'} | ${r.staleDropped} / ${r.staleAudio} | ${r.reasks} | ${r.filledCorrectly ? (r.exact ? 'yes' : `as heard: ${r.dom}`) : `no (heard ${(r.vadSegments || []).join(' ') || JSON.stringify(r.transcript)})`} |`).join('\n');

const sc = bi?.scenarios || {};
const scen = (bi?.results || []).filter(r => /^S2/.test(r.name));
const scenRows = scen.map(r => `| ${r.name.replace(/^S2[a-z]: /, '')} | ${r.ok ? 'PASS' : 'FAIL'} | ${r.detail.replace(/\|/g, '/').slice(0, 110)} |`).join('\n');

const doc = `# Phase 3 results

Generated by \`npm run phase3\` on ${localDate(bi?.at)}${DOC_ONLY ? ' (document rebuilt from the artifacts of that run)' : ''}.

**Verdict: ${overall ? 'PASS' : 'INCOMPLETE'}**

| Suite | Result | Detail |
|---|---|---|
| Local self-test | ${status.selftest ?? 'not run'} | manifest, contracts, parse, secrets, plumbing |
| Barge-in core (pure, Node) | ${status.core ?? 'not run'} | ${count(core)} |
| Delayed frames / stale tail / late timestamps (plumbing, loopback stub) | ${status.stub ?? 'not run'} | ${count(stub)} |
| Real interruptions + scenarios (exit criterion) | ${status.bargein ?? 'not run'} | ${count(bi)} |
| Phase 2 full form by voice (regression) | ${status.voicefill ?? 'not run'} | ${count(vf)} |

## The exit criterion, measured

> *stop latency p95 < 300 ms across 20 interruptions; 0 stale-audio playbacks;
> 0 re-asks; double-interrupt resolves to last instruction.*

| Metric | Method | Result |
|---|---|---|
| Interruptions with audio actually stopped | fake-device speech → AudioWorklet VAD → real stop | **${st.n ?? '—'}** (+${st.preAudio ?? 0} bursts before the first audible sample) |
| Barge-in stop latency p50 / p95 / max | mic onset → last non-silent block rendered by the audio graph (output monitor), or stop call returned, whichever later | **${ms(st.p50)} / ${ms(st.p95)} / ${ms(st.max)}** |
| … including this device's output sink buffer, p50 / p95 / max | same, but to the block leaving the output device (getOutputTimestamp); adds \`outputLatency\` = ${ms(st.outputLatencyMs)} on this run's ${process.env.BARGEIN_HEADFUL ? 'real' : 'headless fake'} sink | ${ms(st.sinkP50)} / ${ms(st.sinkP95)} / ${ms(st.sinkMax)} |
| … to stop call returned, p50 / p95 | mic onset → sources stopped | ${ms(st.stopCallP50)} / ${ms(st.stopCallP95)} |
| Stale audio played after interrupt | output monitor after each stop | **${st.staleAudio ?? '—'} / ${bi?.runs?.length ?? '—'}** (${st.staleDropped ?? '—'} stale chunks dropped before decode) |
| Re-asks of answered fields | re-ask counter + ledger scan for a second prompt turn | **${st.reasks ?? '—'} / ${bi?.runs?.length ?? '—'}** |
| Heard ledger known at every audible interruption | word timestamps × playback clock | ${st.heardKnown ?? '—'} / ${st.n ?? '—'} |
| Interrupting speech became the answer (filled and read back as heard) | whisper → fill → read-back pending | **${st.filled ?? '—'} / ${bi?.runs?.length ?? '—'}** (exact 160071 in ${st.exact ?? '—'}; the rest are whisper digit drops, caught by the read-back) |
| Whisper latency per interruption, median | segment end → transcript | ${ms(st.sttMsMedian)} |
| Double-interrupt resolved to last instruction | S2c, 5 trials: correction interrupted by a second correction | **${sc.doubleInterrupt ? `${sc.doubleInterrupt.resolved} / 5` : 'not run'}** (exact 160073 in ${sc.doubleInterrupt?.exact ?? '—'} / 5; the rest are whisper digit drops, caught by the read-back) |
| Illegal state transitions, whole run | DialogMachine | ${st.illegal ?? '—'} |
| Phases covered (first quarter of the prompt / middle / last 40%) | playback clock at stop, as a fraction of the prompt length | ${st.phases ? `${st.phases.early} / ${st.phases.mid} / ${st.phases.late}` : '—'} |

Latency excludes microphone ADC and speaker DAC hardware latency, which the
fake device cannot exhibit; Chrome reported \`outputLatency\` of
${bi?.runs?.find(r => r.outputLatencyMs != null)?.outputLatencyMs ?? '—'} ms on this run. The detector window
(3 blocks × 8 ms) is included. STT model: \`${bi?.model ? path.basename(bi.model) : '—'}\`.

### Every interruption

| run | phase (s) | stop latency (pipeline) | incl. sink buffer | to stop call | heard words | stale dropped / played | re-asks | answer landed |
|---|---|---|---|---|---|---|---|---|
${runRows || '| (not run) | | | | | | | | |'}

### Scenarios

| Check | Result | Detail |
|---|---|---|
${scenRows || '| (not run) | | |'}

## Reproducing

\`\`\`bash
npm run browser        # Chrome for Testing; stable ignores --load-extension
npm run stt:install    # whisper.cpp + model, for the harness STT
npm run phase3         # BARGEIN_RUNS=20 by default
\`\`\`

Raw: \`artifacts/phase3_bargein.json\`, \`artifacts/phase3_stub.json\`, \`artifacts/phase3_core.json\`.
`;
fs.writeFileSync('PHASE3_RESULTS.md', doc);
console.log(`\nWrote PHASE3_RESULTS.md — verdict ${overall ? 'PASS' : 'INCOMPLETE'}\n`);
process.exit(overall ? 0 : 1);
