// One command for Phase 1: run every suite in dependency order and write
// PHASE1_RESULTS.md from the artifacts they produce.
//
// Ordered cheapest-first so a broken scanner is reported in seconds rather than
// after a full round of real synthesis.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';

const run = (args, env = {}) =>
  spawnSync('node', args, { stdio: 'inherit', env: { ...process.env, ...env } });

const STEPS = [
  { id: 'selftest',   label: 'local self-test',                         args: ['tools/selftest.mjs'],           needs: 'none' },
  { id: 'fieldgraph', label: 'FieldGraph + prompts (real Chrome)',      args: ['tools/test_fieldgraph.mjs'],    needs: 'chrome' },
  { id: 'forms',      label: 'real third-party forms',                  args: ['tools/test_real_forms.mjs'],    needs: 'network' },
  { id: 'e2e',        label: 'end-to-end through real Rime',            args: ['tools/test_e2e.mjs'],           needs: 'rime + chrome-for-testing' },
  { id: 'exit',       label: 'PRD Phase 1 exit criterion',              args: ['tools/test_phase1_exit.mjs'],   needs: 'rime + chrome-for-testing' },
];

const status = {};
let n = 0;
for (const s of STEPS) {
  n++;
  console.log(`\n─── ${n}/${STEPS.length}  ${s.label} ───`);
  const r = run(s.args);
  status[s.id] = r.status === 0 ? 'PASS' : 'FAIL';
  if (r.status !== 0 && s.id === 'selftest') {
    console.error('\nSelf-test failed; later suites would only repeat the noise. Stopping.\n');
    break;
  }
}

const read = (p) => { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } };
const fg = read('artifacts/phase1_fieldgraph.json');
const rf = read('artifacts/phase1_real_forms.json');
const e2 = read('artifacts/phase1_e2e.json');
const ex = read('artifacts/phase1_exit.json');

const count = (o) => o ? `${o.results.filter(r => r.ok ?? r.status === 'PASS').length} pass / ${o.results.filter(r => !(r.ok ?? r.status === 'PASS')).length} fail` : 'not run';
const overall = Object.values(status).every(v => v === 'PASS') && Object.keys(status).length === STEPS.length;

let transcript = '';
if (ex?.transcripts) {
  for (const [name, t] of Object.entries(ex.transcripts)) {
    transcript += `\n**${name}** — ${t.scanned} fields found\n\n`;
    for (const s of t.spoken) {
      transcript += `${String(s.index + 1).padStart(2)}. \`[${s.type}]\` **${s.label}** _(via ${s.labelSource})_\n`;
      transcript += `    - spoke: ${String(s.text).replace(/\s+/g, ' ')}\n`;
      transcript += `    - audio: ${s.chunks} chunks, ${s.audioSec}s\n`;
    }
  }
}

const doc = `# Phase 1 results

Generated by \`npm run phase1\` on ${new Date().toISOString().slice(0, 10)}.

**Verdict: ${overall ? 'PASS' : 'INCOMPLETE'}**

| Suite | Needs | Result | Detail |
|---|---|---|---|
| Local self-test | none | ${status.selftest ?? 'not run'} | manifest, contracts, parse, secrets, plumbing |
| FieldGraph + prompts | Chrome | ${status.fieldgraph ?? 'not run'} | ${count(fg)} |
| Real third-party forms | network | ${status.forms ?? 'not run'} | ${rf ? rf.results.filter(r => r.status === 'PASS').length + ' pass / ' + rf.results.filter(r => r.status === 'FAIL').length + ' fail / ' + rf.results.filter(r => r.status === 'BLOCKED').length + ' blocked' : 'not run'} |
| End-to-end via real Rime | Rime + CfT | ${status.e2e ?? 'not run'} | ${count(e2)} |
| PRD exit criterion | Rime + CfT | ${status.exit ?? 'not run'} | ${count(ex)} |

Provider in force: \`${ex?.provider?.model ?? e2?.provider?.model ?? '?'}\` / \`${ex?.provider?.speaker ?? e2?.provider?.speaker ?? '?'}\` / \`${ex?.provider?.audioFormat ?? '?'}\` / \`segment=${ex?.provider?.segment ?? '?'}\`

## What was read aloud
${transcript || '\n(exit suite not run)\n'}

## Reproducing

\`\`\`bash
npm run browser        # Chrome for Testing; stable ignores --load-extension
npm run phase1
\`\`\`

Raw artifacts: \`artifacts/phase1_*.json\`.
`;

fs.writeFileSync('PHASE1_RESULTS.md', doc);
console.log(`\nWrote PHASE1_RESULTS.md — verdict ${overall ? 'PASS' : 'INCOMPLETE'}\n`);
process.exit(overall ? 0 : 1);
